language: rust
dist: xenial
git:
  depth: 1
env:
  global:
    - PROJECT_NAME: ripgrep
    - RUST_BACKTRACE: 0
addons:
  apt:
    packages:
      # For generating man page.
      - libxslt1-dev
      - asciidoc
      - docbook-xsl
      - xsltproc
      - libxml2-utils
      # Needed for completion-function test.
      - zsh
      # Needed for testing decompression search.
      - xz-utils
      - liblz4-tool
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  file_glob: true
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "$GH_RELEASE_KEY"
